version: "3.8"

services:
  item-api:
    image: item-api:latest
    build:
      context: ./item-api
    ports:
      - "8081:8080"
    networks:
      - my-network

  cupon-api:
    image: cupon-api:latest
    build:
      context: ./cupon-api
    ports:
      - "8080:8080"
    depends_on:
      - item-api
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

