version: "3.8"

services:
  item-api:
    image: item-api:latest
    build:
      context: ./item-api
    ports:
      - "8081:8080"  # Exponer el puerto de la API de Items
    networks:
      - my-network

  cupon-api:
    image: cupon-api:latest
    build:
      context: ./cupon-api
    ports:
      - "8080:8080"  # Exponer el puerto de la API de Cupones
    depends_on:
      - item-api
    networks:
      - my-network

  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin12pract!ce
      MYSQL_DATABASE: my_database
      MYSQL_USER: root
      MYSQL_PASSWORD: admin12pract!ce
    ports:
      - "3306:3306"  # Exponer el puerto de MySQL
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
